FROM golang:1.16 AS builder

WORKDIR /go/src/github.com/alr-lab/practical-test-pyramid-go/mockapi/

COPY . /go/src/github.com/alr-lab/practical-test-pyramid-go/mockapi/

RUN CGO_ENABLED=0 GOOS=linux go build -o mockapi cmd/mockapi/main.go

FROM alpine:latest

COPY --from=builder /go/src/github.com/alr-lab/practical-test-pyramid-go/mockapi/mockapi /mockapi
