FROM golang:1.16-alpine AS builder

ARG bin
ARG dir

WORKDIR ${dir}

COPY . ${dir}

RUN CGO_ENABLED=0 go build -o ${bin} cmd/mockapi/main.go

FROM alpine

ARG bin
ARG dir

COPY --from=builder ${dir}/${bin} /${bin}
